name: podcasts
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  record: ^5.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.37
  audio_video_progress_bar: ^2.0.3
  logger: ^2.4.0
  provider: ^6.1.2
  file_picker: ^8.0.6
  freezed_annotation: ^2.4.4
  firebase_core: ^3.2.0
  path: ^1.9.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  intl: ^0.19.0
  just_audio_background: ^0.0.1-beta.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
