// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC4-yJTIqvflZ4Fxxf9P3D1YVBO44RjRg',
    appId: '1:1030258182554:web:39b7ccadc3ae6c8faa9223',
    messagingSenderId: '1030258182554',
    projectId: 'great-hope',
    authDomain: 'great-hope.firebaseapp.com',
    databaseURL: 'https://great-hope-default-rtdb.firebaseio.com',
    storageBucket: 'great-hope.appspot.com',
    measurementId: 'G-8Y0W1XRVNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXJ5CYLmehU-YWO6UA0GEiJA_ONUWszU',
    appId: '1:1030258182554:android:bdb55372f7aa6c53aa9223',
    messagingSenderId: '1030258182554',
    projectId: 'great-hope',
    databaseURL: 'https://great-hope-default-rtdb.firebaseio.com',
    storageBucket: 'great-hope.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWOtUji8X6J_zTJGQTj0vCfKDTRRZwrO8',
    appId: '1:1030258182554:ios:77887ab3cafb80c8aa9223',
    messagingSenderId: '1030258182554',
    projectId: 'great-hope',
    databaseURL: 'https://great-hope-default-rtdb.firebaseio.com',
    storageBucket: 'great-hope.appspot.com',
    iosBundleId: 'com.example.podcasts',
  );

}